"""empty message

Revision ID: 1bc26a08e976
Revises: e80ad4f773d7
Create Date: 2022-05-05 23:26:54.547414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc26a08e976'
down_revision = 'e80ad4f773d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('co_normal', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('tvoc_normal', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tvoc_normal')
    op.drop_column('users', 'co_normal')
    # ### end Alembic commands ###
