name: cicd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Build
      run: |
        python3 -m venv .env
        source .env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip list

    - name: Testing
      run: |
        source .env/bin/activate
        pytest tests.py

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   needs: deploy-staging
  #   steps:
  #   - name: deploy prod
  #     uses: appleboy/ssh-action@v0.1.3
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.SSH_USER}}
  #       key: ${{ secrets.DO_KEY }}
        
  #       script: |
  #         cd ${{ secrets.SDIR}}
  #         source ${{ secrets.SN}}